paths:
    cache: app/cache
    config: app/config
    database: app/database
    web: public_html
    themebase: public_html/theme
    files: public_html/files
    view: public_html/bolt-public/view

extensions:
    - RSSAggregator\RssAggregatorExtension
